### ISSUE TITLE
最近好像上不去了，是不是更换策略了？

### ISSUE THREAD

**Issue by syrilzhang** [renbaoke/h3c#1]
不知道能不能更新一下，一直offline

**Comment by bluuuuer** [comment]
同问，我寝室的没问题，妹子寝室的一直OFFLINE

**Comment by renbaoke** [comment]
你们是哪个专业的？wireshark抓包分析一下

**Comment by renbaoke** [comment]
我已经毕业了，没有这个环境了

**Comment by syrilzhang** [comment]
我抓包分析过了，我发现一点区别，就是之前每次EAP START，认证服务器第一次REQUEST请求用户名时，Inode客户端返回给服务器的Identifity都不一样，就是等号前的部分
如

> Identity (41 bytes): \006\abjQ7SE8BZ3MqHhs3clMregcDY3Y=  xxxx555
> 下一次变成了
> 
> Identity (41 bytes): \006\aOGcMHBkGMiN6SxxjIFR+KpyZHQY= xxxx555

但是路由器始终是返回一个值，中间没有任何服务器请求key，加密之类的，请问师兄这是什么协议啊？应该是这个地方出问题了才对。

（在其它地方，密码返回等等都是正确的，只有返回用户名这个地方有点问题）
请教师兄
还有前面的那一长条又是什么意思呢

**Comment by renbaoke** [comment]
是用来标识版本的，在h3c.h中有定义，可能版本更新了，所以这个会不一样。

**Comment by syrilzhang** [comment]
师兄我已经交叉编译完毕新的小米路由可执行文件了，谢谢师兄支持~
