### ISSUE TITLE
请问你们的小米mini路由器还能用么？我的突然不能用了

### ISSUE THREAD

**Issue by syrilzhang** [renbaoke/h3c#7]
如果有问题，可能需要重新升级修正了

**Comment by haswelliris** [comment]
坐标慎6，这学期回来又重新开始折腾路由器， 所以还是来瞎参合一下。
自从今年五月份某次路由断电重启后，就无法使用最新的含MD5方法的版本通过h3c验证了。之后换成15年11月编译的老版本，详见[此文中提到的h3c程序](http://bbs.xiaomi.cn/t-11720472-1-o0)，用echo的方式就可以通过验证了。
现在的情况是，老版本使用-p参数输入密码会出现Bus error，无法正常运行。使用echo "密码"|....的方式会出现“Failed to echo_off: Inappropriate ioctl for deviceFailed to echo_on: Inappropriate ioctl for devicePassword for xxxx”的错误提示，但仍能正常通过验证。 所以将就用着。
最新含md5版本的用上述两个运行方式都无法成功通过h3c验证，始终出现“You are now OFFLINE.”。但这个版本我从去年11月到今年上半年一直都是正常使用的，差不多在你发问那段时间也不能用了。
目前只发现慎6有这个情况，不知道你情况如何。另外，上两周也出现了极路由大面积无法通过验证的情况，他们很多把版本号改成7.0那个就可以了，或者一天自己恢复。
感觉很玄学，毕竟这个源的老版本还可以用，今晚抓包研究下。

**Comment by haswelliris** [comment]
坐标慎6，已经解决并连上
方法是，回退到15年6月12号提交的版本，对应版本sha1是 816a34bbe244e95116b4b85b1f07342fae7fdc0c 。这个版本不包含任何md5验证的代码，重新交叉编译后，已经在k2p上正常使用了。
windows下抓取iNode验证包分析他密码是加密的了，但还不确定用的是md5。
总之，现在路由器上用不包含md5验证的版本就能正常上。
情况暂时是这样，需要编译好的，不包含md5验证的老版本可以去我fork的源上下载。

**Comment by renbaoke** [comment]
其实对认证用的加密算法我也没有仔细研究过，加密这一块是我从别人那里看来的，有时间了反编译一下官方的客户端把加密算法搞清楚，以后就不会出现认证失败的问题了。
